var sslc = {
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "Name": "UDUPI", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;8013<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;8058<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;16071<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;6852<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;7537<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;14389<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;89.53<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;1<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;84.4<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;6<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;4<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 74.746049, 13.332320, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "SIRSI", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;4582<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;4633<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;9215<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;3955<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;4183<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;8138<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;88.31<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;2<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;85.3<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;4<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;9<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 74.850004, 14.616704, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "HASSAN", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;11783<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;11968<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;23751<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;9722<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;10685<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;20407<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;85.92<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;3<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;81.32<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;9<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;18<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 76.100466, 13.003326, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "TUMKUR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;12312<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;11085<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;23397<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;10305<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;9780<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;20085<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;85.84<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;4<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;79.04<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;19<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;5<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.101223, 13.338583, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "CHIKODI", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;18933<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;15776<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;34709<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;15830<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;13939<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;29769<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;85.77<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;5<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;87.01<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;2<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;1<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 74.587859, 16.429194, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "UTTARA KANNADA", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;5040<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;5036<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;10076<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;4089<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;4540<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;8629<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;85.64<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;6<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;84.75<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;5<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;12<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 74.780519, 14.709231, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "MANGALORE", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;15532<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;15769<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;31301<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;12351<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;14330<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;26681<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;85.24<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;7<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;78.3<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;21<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;8<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 74.855960, 12.914143, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "MANDYA", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;12271<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;11903<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;24174<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;9977<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;10606<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;20583<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;85.15<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;8<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;85.53<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;3<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;3<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 76.895803, 12.524200, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "RAMNAGARA", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;6972<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;6779<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;13751<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;5692<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;5931<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;11623<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;84.52<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;9<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;77.23<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;26<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;19<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.470199, 12.600260, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "HAVERI", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;9285<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;9609<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;18894<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;7507<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;8283<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;15790<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;83.57<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;10<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;74.31<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;33<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;29<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.400002, 14.800004, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "CHICKAMAGALUR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;7137<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;7563<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;14700<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;5754<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;6523<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;12277<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;83.52<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;11<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;78.23<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;22<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;15<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.770889, 13.312320, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "MYSORE", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;18670<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;18692<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;37362<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;14828<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;16042<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;30870<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;82.62<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;12<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;79.79<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;16<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;26<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 76.639384, 12.295811, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "KODAGU", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;3656<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;3834<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;7490<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;2892<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;3289<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;6181<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;82.52<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;13<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;80.09<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;12<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;7<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.738189, 12.424423, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BELGAUM", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;15663<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;14485<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;30148<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;12472<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;12407<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;24879<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;82.52<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;14<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;80.84<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;11<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;13<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 74.504673, 15.850363, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "CHITRADURGA", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;11145<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;10656<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;21801<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;8933<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;8921<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;17854<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;81.9<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;15<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;79.58<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;17<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;15<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 76.400361, 14.222091, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BAGALKOTE", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;12810<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;10354<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;23164<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;10183<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;8767<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;18950<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;81.81<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;16<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;82.81<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;7<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;6<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.696247, 16.185016, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "DAVANAGERE", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;11747<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;12050<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;23797<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;9307<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;10056<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;19363<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;81.37<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;17<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;80.01<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;14<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;27<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.923840, 14.466348, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BANGALORE RURAL", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;6702<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;6383<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;13085<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;5243<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;5372<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;10615<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;81.12<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;18<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;87.43<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;1<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;2<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.699423, 13.198542, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "SHIMOGA", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;10743<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;11979<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;22722<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;8394<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;10005<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;18399<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;80.97<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;19<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;77.71<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;24<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;14<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.568102, 13.929930, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "DHARWAD", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;12566<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;12207<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;24773<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;9628<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;10194<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;19822<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;80.01<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;20<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;80.05<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;13<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;23<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.007811, 15.458924, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "KOLAR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;10596<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;10213<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;20809<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;8067<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;8545<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;16612<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;79.83<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;21<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;81.46<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;8<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;30<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 78.132560, 13.135737, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "GADAG", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;7491<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;6477<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;13968<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;5663<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;5438<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;11101<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;79.47<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;22<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;75.97<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;27<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;33<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.631284, 15.428782, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "RAICHUR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;10812<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;8507<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;19319<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;8265<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;7014<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;15279<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;79.09<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;23<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;77.79<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;23<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;24<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.354362, 16.207022, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BANGALORE SOUTH", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;28233<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;28254<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;56487<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;20745<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;23549<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;44294<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;78.41<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;24<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;75.31<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;30<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;22<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.594566, 12.971599, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BELLARY", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;14254<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;11953<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;26207<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;10824<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;9692<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;20516<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;78.28<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;25<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;75.5<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;29<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;21<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 76.918737, 15.138543, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "KOPPAL", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;8091<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;6983<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;15074<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;6250<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;5507<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;11757<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;78<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;26<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;78.42<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;20<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;31<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 76.153348, 15.339572, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BANGALORE NORTH", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;23137<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;22189<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;45326<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;16954<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;18102<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;35056<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;77.34<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;27<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;79.98<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;15<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;11<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.594565, 12.971599, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "CHAMARAJANAGAR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;5300<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;5446<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;10746<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;3882<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;4392<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;8274<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;77<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;28<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;79.34<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;18<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;20<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 76.950003, 11.916701, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "MADHUGIRI", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;7159<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;6928<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;14087<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;5285<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;5544<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;10829<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;76.87<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;29<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;74.59<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;31<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;17<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.209201, 13.660604, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "GULBARGA", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;18290<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;15199<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;33489<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;12894<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;11558<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;24452<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;73.02<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;30<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;74.53<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;32<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;25<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 76.834296, 17.329736, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "CHIKKABALLAPUR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;8492<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;7776<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;16268<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;6019<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;5849<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;11868<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;72.95<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;31<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;77.67<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;25<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;28<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.730402, 13.426081, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BIJAPUR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;16147<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;11619<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;27766<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;11054<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;8867<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;19921<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;71.75<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;32<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;80.88<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;10<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;16<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 75.715343, 16.824020, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "YADGIR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;5750<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;3809<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;9559<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;3888<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;2783<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;6671<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;69.79<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;33<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;75.68<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;28<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;32<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.140539, 16.764988, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BIDAR", "Description": "<div><span class=\"l\">Boys Appeared:<\/span>&nbsp;10807<\/div><div><span class=\"l\">Girls Appeared:<\/span>&nbsp;10344<\/div><div><span class=\"l\">Total Appeared:<\/span>&nbsp;21151<\/div><div><span class=\"l\">Boys Passed:<\/span>&nbsp;6552<\/div><div><span class=\"l\">Girls Passed:<\/span>&nbsp;6841<\/div><div><span class=\"l\">Total Passed:<\/span>&nbsp;13393<\/div><div><span class=\"l\">Pass % (2012):<\/span>&nbsp;63.32<\/div><div><span class=\"l\">District Position (2012):<\/span>&nbsp;34<\/div><div><span class=\"l\">Pass % (2011):<\/span>&nbsp;53<\/div><div><span class=\"l\">District Position (2011):<\/span>&nbsp;34<\/div><div><span class=\"l\">District Position (2010):<\/span>&nbsp;34<\/div>" }, "geometry": { "type": "Point", "coordinates": [ 77.519726, 17.920002, 0.000000 ] } }

]
};
